-- Expand WorkStatus and InvoiceStatus enums to support all master status options
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'NEAR_EXPIRED';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'RENEWAL_PROCESS';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'NOT_STARTED';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'PROGRESS';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'CLOSED';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';

ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'NEAR_EXPIRED';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'RENEWAL_PROCESS';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'NOT_STARTED';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'PROGRESS';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'DONE';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'CLOSED';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
